# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'filtro-tempo-real' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for filtro-tempo-real
pod 'Alamofire'

end
